stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
    - src/preprocessing.py
    outs:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv
  feature_engineering:
    cmd: python src/featurize.py
    deps:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_train.csv
    - data/y_test.csv
    - src/featurize.py
    outs:
    - data/X_test_fe.csv
    - data/X_train_fe.csv
    - data/y_train_fe.csv
    - data/y_test_fe.csv
  train:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    - data/X_test_fe.csv
    - data/X_train_fe.csv
    - data/y_test_fe.csv
    - data/y_train_fe.csv
    outs:
    - mlflow/best_model
  build_image:
    cmd: docker build -t student-dropout-model -f ./docker/Dockerfile .
    deps:
      - docker/Dockerfile
      - docker/requirements.txt
      - mlflow/best_model/model
  deploy:
    cmd: bash docker/deploy.sh
    deps:
      - mlflow/best_model/model
  healthcheck:
    cmd: python src/health_check.py
    deps:
      - src/health_check.py
      - mlflow/best_model/model